users = [
{
"user_id": 0,
"name": "Cecil Palmer",
"user_url": "https://randomuser.me/api/portraits/men/90.jpg",
"email": "user.email@gmail.com",
"id": "user",
"password": "1234",
"phone": "123-345-678",
},
{
"user_id": 1,
"name": "Lillian Jackson",
"user_url": "https://randomuser.me/api/portraits/women/3.jpg",
"email": "user.email@gmail.com",
"id": "user",
"password": "1234",
"phone": "123-345-678",
},
{
"user_id": 2,
"name": "Becky Larson",
"user_url": "https://randomuser.me/api/portraits/women/45.jpg",
"email": "user.email@gmail.com",
"id": "user",
"password": "1234",
"phone": "123-345-678",
},
{
"user_id": 3,
"name": "Lucy King",
"user_url": "https://randomuser.me/api/portraits/women/24.jpg",
"email": "user.email@gmail.com",
"id": "user",
"password": "1234",
"phone": "123-345-678",
},
{
"user_id": 4,
"name": "Flenn Ramirez",
"user_url": "https://randomuser.me/api/portraits/men/63.jpg",
"email": "user.email@gmail.com",
"id": "user",
"password": "1234",
"phone": "123-345-678",
},
{
"user_id": 5,
"name": "Darren Freeman",
"user_url": "https://randomuser.me/api/portraits/men/53.jpg",
"email": "user.email@gmail.com",
"id": "user",
"password": "1234",
"phone": "123-345-678",
},
{
"user_id": 6,
"name": "Terry Watts",
"user_url": "https://randomuser.me/api/portraits/men/1.jpg",
"email": "user.email@gmail.com",
"id": "user",
"password": "1234",
"phone": "123-345-678",
},
{
"user_id": 7,
"name": "Phillip Reynolds",
"user_url": "https://randomuser.me/api/portraits/men/11.jpg",
"email": "user.email@gmail.com",
"id": "user",
"password": "1234",
"phone": "123-345-678",
},
{
"user_id": 8,
"name": "Celina Williams",
"user_url": "https://randomuser.me/api/portraits/women/94.jpg",
"email": "user.email@gmail.com",
"id": "user",
"password": "1234",
"phone": "123-345-678",
},
{
"user_id": 9,
"name": "Brandie Kuhn",
"user_url": "https://randomuser.me/api/portraits/women/14.jpg",
"email": "user.email@gmail.com",
"id": "user",
"password": "1234",
"phone": "123-345-678",
}
]